### ISSUE TITLE
Opam?

### ISSUE THREAD

**Issue by spitters** [tchajed/coq-record-update#1]
This seems like a cool idea.
What are your plans on maintaining it?
Should it be an opam package, or move to 
https://github.com/coq/stdlib2/
at some point.

**Comment by spitters** [comment]
Sounds like you need some help from the Coq gurus. @Zimmi48, @maximdenes any suggestions?

**Comment by Zimmi48** [comment]
@spitters The problem is that both Coq gurus you mention are not opam users but Nix users instead (I use opam only when providing support to others). The actual Coq + opam gurus are rather @clarus, @ejgallego and @gares.
Note that I have not been moving very fast on adding opam files to packages in Coq community because I was waiting to see what the work of @ejgallego on building Coq packages with dune would yield (in particular, it should be possible to generate the opam files automatically in the future).

**Comment by ejgallego** [comment]
That's indeed the idea @Zimmi48 , it is likely still not gonna happen before 2019, but hopefully we should use Dune built-in support for generation of OPAM packages.

**Comment by Zimmi48** [comment]
FWIW there is now a template opam file in https://github.com/coq-community/manifesto/tree/master/templates, along with a few examples. The Docker+opam setup that you use in your `.travis.yml` file may also be used to check that the opam file is correct. If you want to, I may open a PR adding both.

**Comment by anton-trunov** [comment]
Hi! I'm willing to provide an `opam` file, but I'd need an `install` make target. I'll open a separate issue for this, since it's not really opam-specific.

**Comment by gliptak** [comment]
https://coq.inria.fr/opam/released/packages/

**Comment by spitters** [comment]
@Zimmi48 does this mean this package is also in CI, and will be added to coq platform?
I forgot where I can find the list of packages that will be in platform.
If not, please let me know where to propose this.

**Comment by Zimmi48** [comment]
@spitters No, it's not in CI and it won't be automatically in the platform. There isn't yet any list of platform packages nor any place to request inclusion. This should come rather soon. I'll let you know when that's the case.

**Comment by spitters** [comment]
Thanks.  Is there a preferred way to get it in CI?

**Comment by tchajed** [comment]
I now understand opam and the templates well enough to put this on opam and get it into the coq-opam repo.

**Comment by spitters** [comment]
From the discussion, it seems this is already in released, but that does
not imply CI and Coq platform yet.

**Comment by Zimmi48** [comment]
How to get a project included in Coq's CI is documented here: https://github.com/coq/coq/blob/master/dev/ci/README-users.md
But it's not clear to me whether this is really useful to do. In particular, it's very possible that this won't be a requirement to get into the platform.

**Comment by spitters** [comment]
Being in CI has been very good for us at corn/math-classes.

We have a couple of projects in https://github.com/AU-COBRA that depend on record-update, so we'd like it not to break :-)

**Comment by tchajed** [comment]
This is now finally fixed, by adding an opam configuration and adding it to the Coq opam registry in https://github.com/coq/opam-coq-archive/pull/1334. Thanks for pushing for it @spitters!

**Comment by spitters** [comment]
@tchajed Thanks. Note that it's in opam, but still not in CI, if I understand @Zimmi48 correctly.

**Comment by tchajed** [comment]
I wouldn't be too concerned about breakage, since I still test this library against Coq nightly, and it's tested as part of building Perennial in Coq CI as well. If something does break, it's likely to be fixed within a couple days of getting merged to Coq.

**Comment by spitters** [comment]
Great! thanks.

**Comment by Zimmi48** [comment]
Oh right, since this is a dependency of Perennial (installed as a submodule), you can consider that this is actually already in CI.
