### ISSUE TITLE
Fails if a field is named "x".

### ISSUE THREAD

**Issue by richardlford** [tchajed/coq-record-update#10]
With this code:

```
Record X := mkX { A: nat; B: nat; x: bool; }.
Instance etaX : Settable _ := settable! mkX <A; B; x>.

```
I get this error when processing the Instance statement:

> Error: No applicable tactic.

Any other field name seems to work. I tried debugging this but was unable to find the cause of the problem.

**Comment by tchajed** [comment]
Thanks for the report and test case! Should work now.

There was something really subtle going on in Ltac where a `destruct x` was meant to destruct a variable bound by a `match goal` but instead got the global reference `x`. @ppedrot would probably say this is the sort of thing Ltac2 is meant to solve.
