### ISSUE TITLE
Published version of coq-record-update cannot be used with coq 8.13

### ISSUE THREAD

**Issue by MackieLoeffel** [tchajed/coq-record-update#24]
The opam file of the published 0.3.0 says that it is not compatible with coq 8.13: https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-record-update/coq-record-update.0.3.0/opam#L19
which leads to errors like the following when combining `coq-record-update` with a dependency that requires coq 8.13.
```
 ...
  - ... → coq-record-update >= 0.3.0 → coq (< 8.13~ & = dev) → ocaml < 4.06.0
        base of this switch (use `--unlock-base' to force)
Your request can't be satisfied:
  - No available version of coq satisfies the constraints
```

However, the [opam file](https://github.com/tchajed/coq-record-update/blob/master/coq-record-update.opam) in this repository says that 0.3.0 is compatible with coq 8.13. Would it be possible to publish a version to `coq-released` that says that it is compatible with coq 8.13?

**Comment by tchajed** [comment]
Sorry about that, I always have trouble upstreaming the opam config to that repo.

**Comment by MackieLoeffel** [comment]
Thanks for the fast solution! Now the installation works with coq 8.13.
