### ISSUE TITLE
Record not being updated, what I'm doing wrong?

### ISSUE THREAD

**Issue by dhilst** [tchajed/coq-record-update#33]
I have this code

```coq
Record foo := { bar : int }.
Instance fooEtaState : Settable _ := settable! Build_foo <bar>.
Lemma foo_test : set bar (fun _ => 1) {| bar := 0 |} = {| bar := 0|}.
Proof.
  unfold set.
  easy.
Qed.
```

After unfolding set I got this

```
  {| bar := {| bar := 0 |}.(bar) |} = {| bar := 0 |}
```

So the update function is gone, I think I'm missing something really obvious but have no idea how to debug this

**Comment by tchajed** [comment]
This works for me, so I suspect you're using primitive projections and running into #31. coq-record-update currently doesn't support primitive projections, and unfortunately I'm not sure how to fix it yet.

For what it's worth, you can leave primitive projections on globally and disable them just for `foo` by adding `#[projections(primitive=no)]` before the record declaration.

**Comment by dhilst** [comment]
Yes, I'm definitely using primitive projections, thank you for the fast answer. I will close the issue.
